scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8086']
  - job_name: 'postgresql'
    metrics_path: '/metrics'  
    static_configs:
      - targets: ['exporter:9187']
