image: maven:3-adoptopenjdk-11
stages:          
  - build
  - deploy

verify:
  stage: build
  script:
    - 'mvn  clean install'
    - 'mvn package'
  only:
    refs:
      - merge_requests



build-deploy-docker:
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u johnskyi --password-stdin 89taman89 
  script:
    - docker build --pull -t javapro-backend .
    - docker push javapro-backend
  tags:
    - javapro
  only:
    refs:
      - main
  except:
    refs:
      - merge_requests

