stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - main
    - dev
    - merge_request
  except:
    - tags
  script:
    - echo "do package jar..."
    - mvn clean
    - mvn package

main_testing:
  stage: test
  only:
    - main
    - dev
    - merge_request
  except:
    - tags
  script:
    - echo "do test"
    - mvn verify

deploy:
  stage: deploy
  only:
    - main
  except:
    - tags
  script:
    - echo "do deploy"
    - mvn package
    - docker system prune -a -f
    - cd /home/gitlab-runner/ && docker-compose down  && docker-compose up -d
