stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - main
    - dev
  except:
    - tags
  script:
    - echo "do package jar..."
    - mvn package
    - docker build -t social_network .

main_testing:
  stage: test
  only:
    - main
    - dev
  except:
    - tags
  script:
    - echo "do test"
    - mvn verify

additional_testing:
  stage: test
  only:
    - main
    - dev
  except:
    - tags
  script:
    - echo "Do another parallel tests here.."

deploy:
  stage: deploy
  only:
    - main
  except:
    - tags
  script:
    - echo "do deploy"
    - cd /home/gitlab-runner/  && docker-compose up -d
