stages:
  - verify
  - deploy
  - shedule 

shedule-test:
  stage: shedule
  rules:
    - if: $CI_PIPELINE_SOURCE = "push"
  script:
    - cd /home/gitlab-runner/
    - PGPASSWORD="iddqd"  pg_dump --host=localhost --username=javapro --file=backup/dbbackup.tar --format=tar
    - ./mvnw verify

verify:
  stage: verify
  only:
    - dev
    - merge_request
  except:
    - tags
  script:
    - echo "do build, test and package jar"
    - ./mvnw clean verify

deploy:
  stage: deploy
  only:
    - main
  except:
    - tags
  script:
    - echo "do deploy"
    - ./mvnw package -Dmaven.test.skip=true
    - cd /home/gitlab-runner/postgres/
    - docker-compose up -d
    - cd ./../
    - PGPASSWORD="iddqd"  pg_dump --host=localhost --username=javapro --file=backup/dbbackup.tar --format=tar
    - docker-compose build --no-cache
    - docker-compose up -d
    - docker system prune -a -f --volumes

