stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - main
  except:
    - tags
  script:
    - echo "package jar"
    - mvn package
    - mvn install

main_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "do test"

additional_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "Do another parallel tests here.."

deploy-job:
  image: docker:latest
  stage: deploy 
  only:
     - main
  except:
     - tags

  script:
    - echo "Do docker image..."
    - docker build -t social_network .
    - cd /home/gitlab-runner/ && docker-compose up -d

