stages:
  - verify
  - deploy
verify:
  stage: verify
  only:
    - dev
    - merge_request
  except:
    - tags
  script:
    - echo "do build, test and package jar"
    - ./mvnw clean verify

deploy:
  stage: deploy
  only:
    - main
  except:
    - tags
  script:
    - echo "do deploy"
    - ./mvnw package -Dmaven.test.skip=true
    - cd /home/gitlab-runner/
    - docker-compose build --no-cache
    - docker-compose up -d
    - docker system prune -a -f --volumes

