image: maven:3-adoptopenjdk-11
stages:          
  - build
  - deploy

verify:
  stage: build
  script:
    - 'mvn  clean install'
    - 'mvn package'
  only:
    refs:
      - merge_requests



build-deploy-docker:
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker run -d -p 8080:8080 "$CI_IMAGE"
  tags:
    - javapro
  only:
    refs:
      - main
  except:
    refs:
      - merge_requests


