stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - main
  except:
    - tags
  script:
    - echo "do package jar..."
    - mvn package

main_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "do test"

additional_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "Do another parallel tests here.."

deploy:
  stage: deploy
  only:
    - main
  except:
    - tags
  script:
    - echo "do deploy"
    - cd /home/gitlab-runner/ && docker-compose up -d
