stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - main
  except:
    - tags
  script:
    - echo "do package jar..."
    - mvn package
    - docker build -t social_network .
    - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag $CI_REGISTRY_IMAGE CI_REGISTRY_USER/$CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE

main_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "do test"

additional_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "Do another parallel tests here.."

deploy:
  stage: deploy
  only:
    - main
  except:
    - tags
  script:
    - echo "do deploy"
    - cd /home/gitlab-runner/ && docker-compose up -d
