stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - main
  except:
    - tags
  before_script:
    - echo "cleaning old jars"
    - mvn clean
  script:
    - echo "build new image"
    - ./mvnw spring-boot:build-image -Dmaven.test.skip=true

main_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "do test"

additional_testing:
  stage: test
  only:
    - master
  except:
    - tags
  script:
    - echo "Do another parallel tests here.."

deploy:
  stage: deploy
  only:
    - main
  except:
    - tags
  script:
    - echo "do deploy"
    - cd /home/gitlab-runner/ && docker-compose up -d
