version: "3.7"

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=javapro
      - POSTGRES_PASSWORD=iddqd
      - POSTGRES_DB=javapro
  social_network:
    build:
      context: ./builds/zPSnmXEe/0/javapro17/javapro-socialnetwork-studygroup-17/
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./builds/zPSnmXEe/0/javapro17/javapro-socialnetwork-studygroup-17/:./builds/zPSnmXEe/0/javapro17/javapro-socialnetwork-studygroup-17/
    ports:
      - "8086:8086"
    networks:
      - "infrastructure"
  social_network_frontend:
    image: nginx:latest
    volumes:
      - ./builds/BwSi5yiA/0/javapro17/javapro_teams_frontend_original/nginx:/etc/nginx/conf.d
      - ./builds/BwSi5yiA/0/javapro17/javapro_teams_frontend_original/dist:/var/www
      - ./logs/nginx:/var/log/nginx
    container_name: frontend
    ports:
      - "5000:5000"
    networks:
      - "infrastructure"
  grafana:
    build: './builds/zPSnmXEe/0/javapro17/javapro-socialnetwork-studygroup-17/scripts/config/grafana'
    container_name: grafana
    ports:
      - "3000:3000"
    user: "$UID:$GID"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    user: "$UID:$GID"
    volumes:
      - ./builds/zPSnmXEe/0/javapro17/javapro-socialnetwork-studygroup-17/scripts/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  infrastructure:
    driver: "bridge"
  monitoring:
