version: "3.7"
services:
  db:
    image: "postgres:9.6"
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=javapro
      - POSTGRES_PASSWORD=iddqd
      - POSTGRES_DB=javapro
    volumes:
         - ./pgdata:/var/lib/postgresql/data
         - ./backup:/backup
         -  ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    networks:
      infrastructure:
        aliases:
          - postgres
networks:
  infrastructure:
    driver: "bridge"

