debug: true
spring:
  datasource:
    url: jdbc:postgresql://45.134.255.54:5432/javapro?user=javapro&password=iddqd
    driver-class-name: org.postgresql.Driver
    username: javapro
#    platform: postgres
#    initialization-mode: always
#    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false
  liquibase:
    url: jdbc:postgresql://45.134.255.54:5432/javapro?user=javapro&password=iddqd
    user: postgres
    enabled: true
    contexts: dev

  security:
        jwt:
          tokenValidTimeInMinutes: 30
          tokenSecretKey: javapro
          authHeader: Authorization
