version: "3.7"
services:
  social_network:
    build: ./builds/zPSnmXEe/0/javapro17/javapro-socialnetwork-studygroup-17/
    volumes: 
      - ./serverlogs:/logs
    container_name: backend
    ports:
      - "8086:8086"
    networks:
      infrastructure:
        aliases:
          - backend
  social_network_frontend:
    build: ./builds/BwSi5yiA/0/javapro17/javapro_teams_frontend_original/
    volumes:
      - ./builds/BwSi5yiA/0/javapro17/javapro_teams_frontend_original/nginx:/etc/nginx/conf.d
      - ./builds/BwSi5yiA/0/javapro17/javapro_teams_frontend_original/dist:/var/www
      - ./logs/nginx:/var/log/nginx
    container_name: frontend
    ports:
      - "5000:5000"
    networks:
      infrastructure:
        aliases:
          - frontend
  grafana:
    build: ./builds/zPSnmXEe/0/javapro17/javapro-socialnetwork-studygroup-17/scripts/config/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    user: "$UID:$GID"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      infrastructure:
        aliases:
          - grafana
  prometheus:
    build: ./builds/zPSnmXEe/0/javapro17/javapro-socialnetwork-studygroup-17/scripts/config/
    container_name: prometheus
    ports:
      - "9090:9090"
    user: "$UID:$GID"
    volumes:
      - ./builds/zPSnmXEe/0/javapro17/javapro-socialnetwork-studygroup-17/scripts/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      infrastructure:
        aliases:
          - prometheus
  exporter:
    image: wrouesnel/postgres_exporter
    container_name: exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://45.134.255.54:5432/javapro?user=javapro&password=iddqd&sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      infrastructure:
        aliases:
          - exporter
networks:
  infrastructure:
    driver: "bridge"
